name: Build
on: [push, pull_request]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true  # Cancel in-flight jobs for the same branch or PR

env:
    INO_SOCKET_CACHE: "template-socket"

jobs:
    formatting-check:
        name: Formatting Check
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        steps:
            - uses: actions/checkout@v2
            - name: Run clang-format style check for C/C++ programs.
              uses: jidicula/clang-format-action@v3.5.1
              with:
                clang-format-version: '11'
                check-path: '.'
                fallback-style: 'Google'

    compile-cli:
        name: Compile on ${{matrix.os}}
        needs: formatting-check
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Create build folder
              run: mkdir build-emu

            - name: Build WARDuino CLI
              run: cmake .. -D BUILD_EMULATOR=ON ; cmake --build .
              working-directory: build-emu

    fill-out-template:
        name: Fill out template files
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Retrieve version
              id: version
              run: |
                echo "::set-output name=HASH::$(sha1sum Arduino-socket.ino.template | grep '^[^ ]*' -o)"
              working-directory: platforms/Arduino-socket

            - name: Cache filled out templates
              id: cache-ino
              uses: actions/cache@v2
              with:
                path: |
                    platforms/Arduino-socket
                key: ${{ env.INO_SOCKET_CACHE }}-${{ steps.version.outputs.HASH }}

            - name: Fill out Arduino-socket.ino.template
              if: steps.cache-ino.outputs.cache-hit != 'true'
              run: |
                  echo -e "SSID=ssid\nPASSWORD=password" > .config
                  make Arduino-socket.ino
              working-directory: platforms/Arduino-socket

    compile-with-arduino:
        name: (Arduino) Compile on ${{matrix.board.platform-name}}
        needs: [formatting-check, fill-out-template]
        runs-on: ubuntu-latest
        env:
            SKETCHES_REPORTS_PATH: sketches-reports
            SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports
            LIBRARIES: |
                - source-path: ./
                - name: WiFi
                - name: HTTPClient
                - name: PubSubClient
                - name: Adafruit NeoPixel
                - source-url: https://github.com/me-no-dev/AsyncTCP.git
        strategy:
            fail-fast: false
            matrix:
                board:
                    - fqbn: 'esp32:esp32:esp32'
                      platform-name: esp32:esp32
                include:
                    - board:
                        platform-name: esp32:esp32
                      platforms: |
                        # Install ESP32 platform via Boards Manager
                        - name: esp32:esp32
                          source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
                      sketches: |
                        - platforms/Arduino
                        - platforms/Arduino-socket
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Retrieve version
              id: version
              run: |
                echo "::set-output name=HASH::$(sha1sum Arduino-socket.ino.template | grep '^[^ ]*' -o)"
              working-directory: platforms/Arduino-socket

            - name: Get Template Cache
              id: cache-ino
              uses: actions/cache@v2
              with:
                path: |
                    platforms/Arduino-socket
                key: ${{ env.INO_SOCKET_CACHE }}-${{ steps.version.outputs.HASH }}

            - name: Compile sketches
              uses: arduino/compile-sketches@v1
              with:
                  platforms: ${{ matrix.platforms }}
                  fqbn: ${{ matrix.board.fqbn }}
                  sketch-paths: |
                      ${{ matrix.sketches }}
                  libraries: |
                      ${{ env.LIBRARIES }}
                  enable-deltas-report: true
                  sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

            - name: Upload sketches report to workflow artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
                  path: ${{ env.SKETCHES_REPORTS_PATH }}

    compile-with-idf:
        name: (ESP-IDF) Compile on ${{matrix.board.platform-name}}
        needs: formatting-check
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                board:
                    - fqbn: 'esp32:esp32:esp32'
                      platform-name: esp32:esp32
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Create build folder
              run: mkdir build

            - name: Test
              run: ls -l ..
              working-directory: build

            - name: Build WARDuino for ESP-IDF
              uses: espressif/esp-idf-ci-action@main
              working-directory: build
              with:
                  esp_idf_version: latest
                  target: esp32
                  command: cmake .. -D BUILD_ESP=ON & make
                  path: .

